### List configuration
GET http://localhost:8080/configs
Accept: application/json

### List all users
GET http://localhost:8080/users
Accept: application/json

### Create new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "chassidykn",
  "password": "67dSgmgUAAP"
}

### Edit user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "username": "marcasb",
  "password": "hhzgUYupjqBucVrZNRr5W"
}