// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"awesomeProject1/api"
	"awesomeProject1/config"
	"awesomeProject1/db"
	"awesomeProject1/handlers"
	"awesomeProject1/log"
	"awesomeProject1/repository"
	"awesomeProject1/service"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig := config.NewConfig()
	zeroLogger := log.NewZeroLogger()
	getConfigHandler := handlers.NewGetConfigHandler(configConfig, zeroLogger)
	sqlxDB, err := db.NewDb(configConfig)
	if err != nil {
		return App{}, err
	}
	postgresUserRepository := repository.NewPostgresUserRepository(sqlxDB)
	postgresUserService := service.NewPostgresUserService(postgresUserRepository)
	getUsersHandler := handlers.NewGetUsersHandler(postgresUserService, zeroLogger)
	postUsersHandler := handlers.NewPostUsersHandler(postgresUserService, zeroLogger)
	editUserHandler := handlers.NewEditUserHandler(postgresUserService, zeroLogger)
	apiApi := api.NewApi(getConfigHandler, getUsersHandler, postUsersHandler, editUserHandler)
	app := NewApp(apiApi)
	return app, nil
}
